"use client";

import { createContext, ReactNode, useContext, useState } from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const en: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "How It Works",
  "nav.advantages": "Why Sui",
  "nav.pools": "Pools",
  "nav.simulator": "Simulator",
  "nav.yield": "Yield Explorer",
  "nav.leaderboard": "Leaderboard",
  "nav.profile": "Profile",
  "nav.faq": "FAQ",
  "nav.faucet": "Faucet",
  "nav.demo": "Demo",
  "nav.yieldDemo": "Yield Engine",
  "nav.connectWallet": "Connect Wallet",

  "about.badge": "What is Suivan?",
  "about.title": "Community savings, rebuilt for",
  "about.titleHighlight": "Sui",
  "about.problemTitle": "Traditional ROSCA Gaps",
  "about.problemSubtitle": "Trust and coordination issues",
  "about.problem1.title": "Commitment risk",
  "about.problem1.desc": "Members need clear incentives to complete every cycle.",
  "about.problem2.title": "Idle funds",
  "about.problem2.desc": "Capital can sit unused between contributions and payouts.",
  "about.problem3.title": "Manual records",
  "about.problem3.desc": "Status, turns, and payments are hard to verify at scale.",
  "about.problem4.title": "Limited reach",
  "about.problem4.desc": "Local groups need infrastructure to coordinate globally.",
  "about.solutionTitle": "Suivan Direction",
  "about.solutionSubtitle": "Composable frontend for Sui ROSCA pools",
  "about.solution1.title": "Collateral visibility",
  "about.solution1.desc": "Surface commitment state without hardcoding old contract logic.",
  "about.solution2.title": "Yield signals",
  "about.solution2.desc": "Show APY and idle-fund opportunities through modular data boundaries.",
  "about.solution3.title": "Transparent cycle state",
  "about.solution3.desc": "Expose participant progress, payouts, and contribution status clearly.",
  "about.solution4.title": "Global pool UX",
  "about.solution4.desc": "Explain Arisan as a local ROSCA expression while keeping the product global.",
  "about.quote": "Community wealth works when rules are visible, cycles are clear, and members can coordinate across borders.",
  "about.quoteBrand": "Suivan",
  "about.quoteEnd": "makes that interface legible.",
  "about.cta": "See How It Works",

  "faq.badge": "FAQ",
  "faq.title": "Frequently Asked Questions",
  "faq.subtitle": "Everything you need to know about Suivan, ROSCA pools, and how to start saving on Sui.",

  "faq.q1": "What is Suivan?",
  "faq.a1": "Suivan is an on-chain ROSCA protocol built on Sui Move. It brings traditional rotating savings into DeFi. Community members contribute monthly, winners are randomly selected via Seal RNG, and idle funds earn yield across Sui protocols. No treasurer, no middleman, fully transparent smart contracts.",

  "faq.q2": "What is ROSCA?",
  "faq.a2": "ROSCA (Rotating Savings and Credit Association) is a global savings model practiced by billions — known as Arisan in Indonesia, Chit Fund in India, Tanda in Mexico, and many more. Members contribute a fixed amount each cycle. Each cycle, one member receives the entire pooled payout. This repeats until everyone has had a turn.",

  "faq.q3": "How do I start using Suivan?",
  "faq.a3": "Just connect your Sui wallet. Installation is free and takes seconds. Head to /faucet to claim 500 free USDC. Then explore /pools, pick one that fits your budget, and join. All transactions are sponsored. You pay zero gas fees.",

  "faq.q4": "Why Sui? What makes it different?",
  "faq.a4": "Sui's object model makes every pool a live on-chain entity. Sub-second finality means instant settlement. Gas fees are zero, fully sponsored by the protocol. Seal RNG provides verifiable fair winner selection. Walrus stores pool metadata permanently. No other chain offers this combination.",

  "faq.q5": "How does the collateral system work?",
  "faq.a5": "Every participant deposits 125% of their remaining commitment upfront. This guarantees everyone pays. If you miss a payment, your collateral is slashed proportionally. If you complete all cycles, your full collateral is returned plus your share of the pool's yield.",

  "faq.q6": "How are winners selected?",
  "faq.a6": "Winners are selected randomly each cycle using Seal RNG. Anyone can verify the draw was fair on-chain. No admin, no manual drawing, no bias.",

  "faq.q7": "How does yield work?",
  "faq.a7": "While funds sit idle between cycles, our Yield Engine deploys them across Sui DeFi protocols (DeepBook V3, Cetus, Scallop, Aftermath, Navi, Bluefin, Turbos) to earn available APY. Yield accrues to the pool and is distributed as a jackpot via verifiable Gacha draw at pool end. Visit the Yield Explorer to see live APY data from DeFiLlama across 10+ protocols.",

  "faq.q8": "Is Suivan non-custodial?",
  "faq.a8": "Yes. You control your assets at all times through your wallet. Smart contracts handle pool logic and collateral. Even the pool creator cannot access other participants' deposits. Every action is on-chain and verifiable.",

  "faq.q9": "What happens if someone defaults?",
  "faq.a9": "If someone misses a payment, their collateral is slashed. The missed amount goes to the pool. The cycle continues. Other members are protected. Enforced entirely by smart contract.",

  "faq.q10": "Are the smart contracts audited?",
  "faq.a10": "The Suivan smart contracts are deployed on Sui testnet and open-source. The code follows Sui Move security best practices. A full third-party audit is planned before mainnet.",

  "faq.q11": "How much does it cost to use Suivan?",
  "faq.a11": "You pay zero gas. Every transaction on Suivan is sponsored by the protocol. Your wallet balance stays untouched. This is made possible by Sui's ultra-low transaction costs, making full sponsorship economically sustainable.",

  "faq.q12": "Can I create my own pool?",
  "faq.a12": "Yes. Connect your wallet and click +Create Pool. Set the deposit amount, number of participants (2-50), and cycle duration. You can add a custom name and description via Walrus. The pool is live immediately.",

  "faq.q13": "What is Walrus and how does Suivan use it?",
  "faq.a13": "Walrus is Sui's decentralized blob storage. Suivan uses it to store pool names and descriptions permanently on-chain. No centralized database. Immutable and verifiable.",

  "faq.q14": "Where can I follow the project?",
  "faq.a14": "Join us on Telegram (t.me/sui_van) and Discord (discord.gg/XxxM958bm). Follow @suivanprotocol on X. Code is open-source on GitHub. We're a Sui Overflow 2026 project and welcome feedback and contributors.",
  "faq.q15": "How does the gacha jackpot work?",
  "faq.a15": "Every month, deposits earn yield via DeepBook V3 flash loan arbitrage. The yield accumulates through the pool's lifetime. At the end, one winner takes everything via weighted gacha draw. Your chance depends on how consistently you paid. Members who miss 2+ payments get zero tickets.",
  "faq.q16": "How is my leaderboard tier calculated?",
  "faq.a16": "Your tier is based on payment punctuality, yield earned, and pools joined. Paying 1st-10th earns most points, 11th-20th medium, after 20th counts late. Tiers: Bronze (0+), Silver (100+), Gold (200+), Platinum (300+), Diamond (400+). Higher tiers multiply your collateral yield. Points also determine gacha tickets — two separate reward systems.",

  "faq.contactTitle": "Still have questions?",
  "faq.contactDesc": "Join the Suivan community channels for updates, feedback, and collaboration.",

  "landing.badge": "Sui Overflow 2026",
  "landing.title": "Global ROSCA Pools.\nZero Gas. Real Yield.",
  "landing.subtitle": "Suivan brings Rotating Savings & Credit Associations (ROSCA) on-chain. A proven informal finance model now in DeFi. Deposit into your pool, earn yield across Sui protocols, and let automation manage the cycles. No gas fees, no middlemen, no lock-ups. Transparent smart contracts with sponsored transactions. Community savings meet DeFi on Sui.",
  "landing.explore": "Explore Pools",
  "landing.how": "How It Works",
  "landing.statPools": "POOLS",
  "landing.statMembers": "MEMBERS",
  "landing.statVolume": "VOLUME",
  "landing.statApy": "AVG APY",
  "landing.whyBadge": "built_on_sui",
  "landing.whyTitle": "Powered by",
  "landing.whySui": "Sui",
  "landing.whyDesc": "Sui's object model turns every ROSCA pool into a live on-chain entity. With zero-gas sponsored transactions and Walrus storage, Suivan makes community finance simple.",
  "landing.feature1Title": "Quick Start",
  "landing.feature1Desc": "Connect any Sui wallet in seconds. Claim 500 USDC from faucet. Start saving immediately.",
  "landing.feature2Title": "Sponsored Tx",
  "landing.feature2Desc": "Zero gas — always. Every transaction is sponsored by the protocol. Start saving without ever paying a fee.",
  "landing.feature3Title": "DeFi Yields",
  "landing.feature3Desc": "Pool funds routed to Sui DeFi protocols. Real APY from DeepBook, Cetus, Scallop, and more.",
  "landing.feature4Title": "Walrus Storage",
  "landing.feature4Desc": "Pool metadata stored on Walrus. Decentralized, tamper-proof, always available.",
  "landing.step1Title": "Join with Google",
  "landing.step1Copy": "Connect any Sui wallet. Installation is free. All gas fees are sponsored by the protocol.",
  "landing.step2Title": "Pick a Pool",
  "landing.step2Copy": "Choose from open ROSCA circles. Review the terms, deposit collateral, and commit to the cycle.",
  "landing.step3Title": "Contribute Monthly",
  "landing.step3Copy": "Each cycle, deposit your share. Track your status: ready, pending, contributed, or paid out.",
  "landing.step4Title": "Earn Yield",
  "landing.step4Copy": "Idle pool funds earn DeFi yield automatically. Composable strategies maximize returns across Sui protocols.",
  "landing.sectionTitle": "Community savings in four steps.",
  "landing.sectionSub": "From zero to yield. No crypto knowledge needed. Just a wallet and a few clicks.",
  "landing.poolsBadge": "live_pools",
  "landing.poolsTitle": "Active ROSCA Circles",
  "landing.poolsDesc": "Browse real pools on Sui. Each pool is an inspectable on-chain object with transparent cycle state.",
  "landing.trustBadge": "security_layer",
  "landing.trustTitle": "Built for trust. Backed by Sui.",
  "landing.trustDesc": "Every contribution, payout, and cycle is recorded on Sui's ledger. Smart contracts enforce the rules. Collateral protects the group. Walrus makes pool data permanent and transparent.",
  "landing.trust1": "Non-Custodial",
  "landing.trust1Desc": "Funds remain in smart contracts. Suivan never holds your assets.",
  "landing.trust2": "Collateral-Backed",
  "landing.trust2Desc": "125% overcollateralization ensures commitment. Miss a payment? Collateral covers the group.",
  "landing.trust3": "Auditable",
  "landing.trust3Desc": "Every cycle, every payout, every yield event. Fully transparent on Sui explorer.",
  "landing.ctaTitle": "Ready to save with your community?",
  "landing.ctaDesc": "Join a ROSCA pool, contribute monthly, and earn yield. No crypto knowledge needed.",
  "landing.ctaButton": "Get Started Free",
  "landing.ctaBadge": "no_wallet_needed",
  "landing.cylinderDesc": "Top-tier {chain} lending protocol with real-time APY from DeFiLlama.",
  "landing.cylinderSupply": "Supply on {name} →",
  "landing.cylinderLive": "LIVE",
  "landing.cylinderSource": "SOURCE",
  "pools.title": "Explore ROSCA Pools",
  "pools.subtitle": "Discover rotating savings pools with visible cycle state, participant progress, and APY signals.",
  "pools.totalPools": "TOTAL POOLS",
  "pools.open": "OPEN",
  "pools.active": "ACTIVE", 
  "pools.usdc": "USDC",
  "pools.create": "+ Create Custom Pool",
  "pools.connectWallet": "Connect wallet to create pool",
  "pools.join": "Join Pool",
  "pools.viewDetails": "View Details",
  "pools.emptyTitle": "No pools found",
  "pools.emptyDesc": "No pools have been created yet. Be the first to create one!",
  "pools.emptyFilter": "There are no {filter} pools at the moment.",
  "pools.joinTitle": "Join {name}",
  "pools.deposit": "Cycle Deposit",
  "pools.collateral": "Required Collateral",
  "pools.collateralDesc": "125% of remaining deposits, returned at cycle end plus yield bonus",
  "pools.estimatedApy": "Estimated APY",
  "pools.coinLabel": "USDC Coin",
  "pools.agree": "By joining, you agree to make monthly deposits for {count} months",
  "pools.createTitle": "Create Custom Pool",
  "pools.totalValue": "Total Pool Value",
  "pools.poolDuration": "Pool Duration",
  "pools.requiredCollateral": "Required Collateral (125%)",

  "detail.back": "Back to Pools",
  "detail.poolInfo": "Pool Information",
  "detail.deposit": "DEPOSIT",
  "detail.members": "MEMBERS",
  "detail.cycle": "CYCLE",
  "detail.funds": "FUNDS",
  "detail.capacity": "Pool Capacity",
  "detail.yieldSection": "Yield and Cycle Signals",
  "detail.yield": "YIELD",
  "detail.estApy": "EST APY",
  "detail.collateral": "COLLATERAL",
  "detail.participants": "Participants ({count})",
  "detail.noParticipants": "No participants yet. Be the first to join!",
  "detail.yourStatus": "Your Status",
  "detail.activeParticipant": "Active Participant",
  "detail.youAreIn": "You are part of this ROSCA pool",
  "detail.collateralLocked": "Collateral Locked",
  "detail.totalDeposited": "Total Deposited",
  "detail.receivedPayout": "Received Payout",
  "detail.yes": "Yes",
  "detail.notYet": "Not yet",
  "detail.makeDeposit": "Make Cycle Deposit",
  "detail.collateralAvailable": "Collateral Available",
  "detail.collateralReturned": "Your collateral + yield bonus has been returned automatically when the pool ended.",
  "detail.notParticipant": "You are not a participant in this pool.",
  "detail.joinThisPool": "Join This Pool",
  "detail.yourWallet": "Your Wallet",
  "detail.usdcBalance": "USDC Balance",
  "detail.coinsAvailable": "{count} coin(s) available",
  "detail.getStarted": "Get Started",
  "detail.connectPrompt": "Connect your wallet to join this pool or view your status",
  "detail.chartDisclaimer": "Simulated projection based on current pool metrics. Real time-series data will appear after multiple cycles.",
  "ai.badge": "SUI YIELD EXPLORER",
  "ai.title": "SUI Yield Explorer",
  "ai.subtitle": "Live APY data from Sui DeFi protocols, deployed via DeepBook V3 flash loan arbitrage.",
  "ai.loading": "Fetching live yields...",
  "ai.errorTitle": "FETCH ERROR",
  "ai.avgApy": "AVG APY",
  "ai.maxApy": "MAX APY",
  "ai.protocols": "PROTOCOLS",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Protocol Yields",
  "ai.trend": "Trend",
  "ai.marketConditions": "Market Conditions",
  "ai.volatilityIndex": "Volatility Index",
  "ai.gasPrice": "Reference Gas Price",
  "ai.direction": "Direction",
  "ai.topProtocol": "Top",
  "ai.howSuivanUses": "How Suivan Deploys Yield",
  "ai.howSuivanUsesDesc": "Pool funds are deployed to Sui DeFi protocols through DeepBook V3 flash loan arbitrage. Execution is automatic and rebalanced continuously.",
  "ai.step1Title": "Withdraw",
  "ai.step1Desc": "Funds are withdrawn atomically. If any step fails, the entire transaction rolls back.",
  "ai.step2Title": "Arbitrage",
  "ai.step2Desc": "Flash loan borrowed from DeepBook. Arbitrage executed across DEX and lending pools simultaneously.",
  "ai.step3Title": "Profit",
  "ai.step3Desc": "Profit goes to the cumulative jackpot. Principal returns to the pool.",
  "ai.step4Title": "Jackpot",
  "ai.step4Desc": "At pool end, one gacha winner takes all accumulated yield. Weighted by on-time payment score.",
  "ai.deepbookTitle": "DeepBook V3",
  "ai.deepbookMidPrice": "Mid Price",
  "ai.deepbookSpread": "Spread",
  "ai.deepbookBidDepth": "Bid Depth",
  "ai.deepbookAskDepth": "Ask Depth",
  "ai.deepbookLink": "View DeepBook Explorer",
  "ai.sortedBy": "Sorted by",
  "ai.howItWorks": "How Suivan Deploys Yield",
  "ai.autoNote": "Execution is automatic. Routes are rebalanced continuously through flash loan arbitrage.",
  "ai.seeDeepBookFlow": "See Full Flow",
  "ai.explorePools": "Explore Pools",
  "demo.badge": "demo_walkthrough",
  "demo.subtitle": "Five steps from zero to yield. No crypto knowledge needed.",
  "demo.step": "Step",
  "demo.step1Detail": "Connect any Sui wallet in seconds. Install, connect, done. All gas fees are sponsored.",
  "demo.step1Action": "Try Google Login",
  "demo.step2Detail": "Browse pools (Small: 10 USDC, Medium: 50 USDC, Large: 100 USDC). Deposit collateral once. All gas is sponsored.",
  "demo.step2Action": "Sponsored Join",
  "demo.step3Detail": "Each cycle, deposit your share. Miss a payment? Collateral is slashed automatically.",
  "demo.step3Action": "Make Deposit",
  "demo.step4Detail": "One participant wins each cycle. Selection uses verifiable Seal RNG. Winner receives all cycle deposits.",
  "demo.step4Action": "Select Winner",
  "demo.step5Detail": "Idle funds earn yield via Sui DeFi. Real APY from DeFiLlama. At pool end, collateral is returned plus your share of the yield.",
  "demo.step5Action": "View Yield Dashboard",
  "demo.feature1Title": "Zero Gas Fees",
  "demo.feature1Desc": "Zero gas, always. Join pools without ever holding SUI.",
  "demo.feature2Title": "DeFi Yield",
  "demo.feature2Desc": "Idle funds earn yield through Sui protocols. Real APY from DeFiLlama.",
  "demo.feature3Title": "On-Chain Metadata",
  "demo.feature3Desc": "Pool details stored on Walrus. Permanent and decentralized.",
  "leaderboard.badge": "LEADERBOARD",
  "leaderboard.title": "Participant Rankings",
  "leaderboard.subtitle": "Ranked by payment punctuality, yield earned, and community reputation. Pay before the 20th to climb the tiers.",
  "leaderboard.statPools": "ACTIVE POOLS",
  "leaderboard.statUsers": "ALL TIME MEMBERS",
  "leaderboard.statEarned": "TOTAL YIELD DISTRIBUTED",
  "leaderboard.statAvgApy": "AVG APY",
  "leaderboard.tierDiamond": "Diamond",
  "leaderboard.tierPlatinum": "Platinum",
  "leaderboard.tierGold": "Gold",
  "leaderboard.tierSilver": "Silver",
  "leaderboard.tierBronze": "Bronze",
  "leaderboard.tierDesc": "Top-tier members with exceptional payment records and high yield accumulation.",
  "leaderboard.cycleTitle": "Current Cycle",
  "leaderboard.cycleDeadline": "Payment Deadline",
  "leaderboard.cycleDrawing": "Winner Drawing",
  "leaderboard.cyclePot": "Winner Pot",
  "leaderboard.yourRank": "Your Rank",
  "leaderboard.yourPoints": "Points",
  "leaderboard.yourYield": "Your Yield",
  "leaderboard.yourTier": "Your Tier",
  "leaderboard.notConnected": "Connect wallet to see your rank",
  "leaderboard.rank": "RANK",
  "leaderboard.member": "MEMBER",
  "leaderboard.tier": "TIER",
  "leaderboard.points": "POINTS",
  "leaderboard.payment": "PAYMENT",
  "leaderboard.yield": "YIELD",
  "leaderboard.onTime": "ON-TIME %",
  "leaderboard.pools": "POOLS",
  "leaderboard.early": "On Time",
  "leaderboard.late": "Late",
  "leaderboard.noData": "No participants yet. Join a pool to appear on the leaderboard.",
  "leaderboard.rulesTitle": "How Ranking Works",
  "leaderboard.rulesPayment": "Monthly Contribution",
  "leaderboard.rulesPaymentDesc": "Each member contributes monthly. Payment must be received by the 20th of every month. Late payments are deducted from collateral.",
  "leaderboard.rulesPoints": "Points System",
  "leaderboard.rulesPointsDesc": "Pay between 1st–10th: +100 pts | 11th–15th: +75 pts | 16th–20th: +50 pts | After 20th (late): +10 pts. Cumulative points determine your tier.",
  "leaderboard.rulesDrawing": "Winner Drawing",
  "leaderboard.rulesDrawingDesc": "Every 25th, one member is randomly selected to receive the total pot (participants × monthly contribution). All members remain in the cycle.",
  "leaderboard.rulesYield": "Yield Calculation",
  "leaderboard.rulesYieldDesc": "Two yields at pool end. Collateral Yield: base return × tier multiplier. Cumulative Yield: pooled from all contributions. Higher tier = bigger multiplier.",
  "leaderboard.rulesGacha": "Gacha Jackpot",
  "leaderboard.rulesGachaDesc": "All yield from deposits is pooled into a jackpot. At the pool's end, one winner is drawn via weighted lottery. Your payment score determines your tickets. More consistent = higher chance. Members who miss 2+ payments get zero tickets.",
  "leaderboard.cta": "Join a Pool",


  "simulator.badge": "SIMULATOR",
  "simulator.title": "How much wallet balance do you need?",
  "simulator.subtitle": "Calculate how much USDC you need before joining a ROSCA pool. No surprises, no hidden costs.",
  "simulator.poolConfig": "Pool Configuration",
  "simulator.depositLabel": "Monthly Deposit (USDC)",
  "simulator.participantsLabel": "Number of Participants",
  "simulator.cycleLabel": "Cycle Duration (days)",
  "simulator.gasSponsor": "Sponsored Transactions",
  "simulator.gasSponsorDesc": "All transactions are sponsored. You never pay gas. Protocol covers it.",
  "simulator.breakdown": "Wallet Requirement Breakdown",
  "simulator.totalUpfront": "Total Upfront Needed",
  "simulator.needToPrepare": "You need to prepare",
  "simulator.deposit": "Cycle Deposit",
  "simulator.collateral": "Collateral (125%)",
  "simulator.gas": "Gas",
  "simulator.gasFree": "All tx sponsored",
  "simulator.usdc": "USDC",
  "simulator.sui": "SUI",
  "simulator.poolSummary": "Pool Summary",
  "simulator.totalPool": "Total Pool Value",
  "simulator.totalCycles": "Total Cycles",
  "simulator.poolDuration": "Pool Duration",
  "simulator.yourPosition": "Your Position",
  "simulator.youPay": "You Pay Per Cycle",
  "simulator.youEarn": "You Earn Total",
  "simulator.compareTitle": "Zero gas on Sui",
  "simulator.compareDesc": "Sui tx cost ~0.0001 SUI (fractions of a cent). Ethereum L1 averages ~$1.50 per tx.",
  "simulator.suiFee": "Sui Fee",
  "simulator.ethFee": "Ethereum Fee",
  "simulator.savings": "Efficiency",
  "simulator.cta": "Explore Real Pools",
  "simulator.collateralNote": "125% of remaining contribution commitment, returned at cycle end",
  "simulator.collateralDetail": "Collateral protects all members. If you miss a payment, the deposit is deducted from your collateral. Unused collateral + proportional yield is returned when the pool ends.",

  "faucet.badge": "TEST FAUCET",
  "faucet.title": "Get Test Tokens",
  "faucet.subtitle": "Claim 500 USDC for testing. All transactions are sponsored with zero gas fees. Explore Suivan pools before mainnet.",
  "faucet.claimUsdc": "Claim 10,000 Test USDC",
  "faucet.claimSui": "Claim 500 USDC",
  "faucet.walletRequired": "Connect your wallet to claim test tokens.",
  "faucet.success": "Tokens claimed successfully!",
  "faucet.error": "Faucet request failed",
  "faucet.cooldown": "Cooldown active. Try again in {time}s.",
  "faucet.description": "All tokens on this page are testnet-only \u2014 no real value. Use them to simulate pool creation, joining, and yield scenarios.",
  "faucet.usdcLabel": "USDC (Testnet)",
  "faucet.usdcDesc": "USDC stablecoin for pool deposits and collateral",
  "faucet.suiLabel": "TEST_SUI",
  "faucet.suiDesc": "Gas sponsored — you never pay",
  "faucet.recentTitle": "Recent Claims",
  "faucet.recentEmpty": "No claims yet. Start by connecting your wallet and minting tokens.",
  "faucet.balanceTitle": "Your Balances",
  "faucet.goToPools": "Go to Pools",

  "profile.badge": "YOUR DASHBOARD",
  "profile.title": "Your Profile",
  "profile.subtitle": "Your on-chain savings journey: pools joined, cycles won, and yield earned across the Sui network.",
  "profile.titleWithAddr": "Your Profile — {addr}",
  "profile.connectPrompt": "Connect your wallet to view your Suivan profile.",
  "profile.statsPools": "Pools Joined",
  "profile.statsWon": "Cycles Won",
  "profile.statsSaved": "Total Saved",
  "profile.statsYield": "Yield Earned",
  "profile.nftTitle": "Achievements",
  "profile.nftEmpty": "No achievements yet. Join a pool to earn your first Suivan achievement.",
  "profile.activityTitle": "Recent Activity",
  "profile.activityEmpty": "No recent activity. Your pool joins, cycle wins, and badge claims will appear here.",
  "profile.noActivity": "No activity yet. Join a pool to get started!",
  "profile.infoTitle": "Account Info",
  "profile.infoAddress": "Wallet Address",
  "profile.infoMemberSince": "Member Since",
  "profile.infoPools": "Active Pools",
  "profile.infoNetwork": "Network",
};

const id: Record<string, string> = {
  "nav.about": "ROSCA",
  "nav.howItWorks": "Cara Kerja",
  "nav.advantages": "Mengapa Sui",
  "nav.pools": "Pool",
  "nav.simulator": "Simulator",
  "nav.yield": "Yield Explorer",
  "nav.leaderboard": "Papan Peringkat",
  "nav.profile": "Profil",
  "nav.faq": "FAQ",
  "nav.faucet": "Faucet",
  "nav.demo": "Demo",
  "nav.yieldDemo": "Mesin Yield",
  "nav.connectWallet": "Hubungkan Dompet",

  "about.badge": "Apa itu Suivan?",
  "about.title": "Tabungan komunitas, dibangun ulang untuk",
  "about.titleHighlight": "Sui",
  "about.problemTitle": "Kekurangan ROSCA Tradisional",
  "about.problemSubtitle": "Masalah kepercayaan dan koordinasi",
  "about.problem1.title": "Risiko komitmen",
  "about.problem1.desc": "Anggota butuh insentif jelas untuk menyelesaikan setiap siklus.",
  "about.problem2.title": "Dana menganggur",
  "about.problem2.desc": "Modal bisa tidak terpakai di antara kontribusi dan pembayaran.",
  "about.problem3.title": "Catatan manual",
  "about.problem3.desc": "Status, giliran, dan pembayaran sulit diverifikasi secara luas.",
  "about.problem4.title": "Jangkauan terbatas",
  "about.problem4.desc": "Kelompok lokal butuh infrastruktur untuk berkoordinasi secara global.",
  "about.solutionTitle": "Arah Suivan",
  "about.solutionSubtitle": "Frontend komposable untuk pool ROSCA di Sui",
  "about.solution1.title": "Visibilitas jaminan",
  "about.solution1.desc": "Tampilkan status komitmen tanpa mengunci logika kontrak lama.",
  "about.solution2.title": "Sinyal yield",
  "about.solution2.desc": "Tampilkan APY dan peluang dana menganggur melalui batasan data modular.",
  "about.solution3.title": "Status siklus transparan",
  "about.solution3.desc": "Tampilkan progres partisipan, pembayaran, dan status kontribusi dengan jelas.",
  "about.solution4.title": "UX pool global",
  "about.solution4.desc": "Jelaskan Arisan sebagai ekspresi ROSCA lokal sambil menjaga produk tetap global.",
  "about.quote": "Kekayaan komunitas bekerja saat aturan terlihat, siklus jelas, dan anggota bisa berkoordinasi lintas batas.",
  "about.quoteBrand": "Suivan",
  "about.quoteEnd": "membuat antarmuka itu mudah dibaca.",
  "about.cta": "Lihat Cara Kerja",

  "faq.badge": "FAQ",
  "faq.title": "Pertanyaan Umum",
  "faq.subtitle": "Semua yang perlu kamu ketahui tentang Suivan, pool ROSCA, dan cara mulai menabung di Sui.",

  "faq.q1": "Apa itu Suivan?",
  "faq.a1": "Suivan adalah protokol ROSCA on-chain di Sui Move. Menghadirkan tabungan bergilir tradisional ke DeFi. Anggota berkontribusi bulanan, pemenang dipilih acak via Seal RNG, dana menganggur menghasilkan yield di protokol Sui. Tanpa bendahara, tanpa perantara, smart contract transparan.",

  "faq.q2": "Apa itu ROSCA?",
  "faq.a2": "ROSCA (Rotating Savings and Credit Association) adalah model tabungan global yang dipraktikkan oleh miliaran orang — dikenal sebagai Arisan di Indonesia, Chit Fund di India, Tanda di Meksiko, dan banyak lagi. Anggota menyetor jumlah tetap setiap siklus. Setiap siklus, satu anggota menerima seluruh pembayaran yang terkumpul. Ini berulang sampai semua mendapat giliran.",

  "faq.q3": "Bagaimana cara mulai menggunakan Suivan?",
  "faq.a3": "Cukup hubungkan Sui wallet. Instalasinya gratis, hanya beberapa detik. Buka /faucet untuk klaim 500 USDC gratis. Lalu jelajahi /pools, pilih sesuai anggaranmu, dan gabung. Semua transaksi disponsori. Kamu tidak pernah bayar gas.",

  "faq.q4": "Kenapa Sui? Apa yang membuatnya berbeda?",
  "faq.a4": "Model object-centric Sui membuat setiap pool menjadi objek on-chain hidup yang bisa kamu periksa kapan saja. Finalitas sub-detik berarti penyelesaian instan. Biaya gas = nol (disponsori). Seal RNG menyediakan pemilihan pemenang acak yang dapat diverifikasi. Walrus menyimpan metadata pool secara permanen. Stack ini mustahil di chain lain.",

  "faq.q5": "Bagaimana sistem jaminan bekerja?",
  "faq.a5": "Setiap peserta menyetor jaminan 125% dari sisa komitmennya. Ini menjamin semua orang bayar. Jika kamu lewatkan pembayaran, jaminan dipotong. Jika selesaikan semua siklus, jaminan penuh kembali plus bagian yield-mu.",

  "faq.q6": "Bagaimana pemenang dipilih?",
  "faq.a6": "Pemenang dipilih acak setiap siklus dengan Seal RNG. Bisa diverifikasi on-chain. Siapa pun bisa cek bahwa undiannya adil. Tanpa admin, tanpa undian manual, tanpa bias.",

  "faq.q7": "Bagaimana yield bekerja?",
  "faq.a7": "Saat dana menganggur di antara siklus, Yield Engine kami menyebarkannya ke protokol DeFi Sui (DeepBook V3, Cetus, Scallop, Aftermath, Navi, Bluefin, Turbos) untuk mendapatkan APY yang tersedia. Yield terkumpul ke pool dan didistribusikan sebagai jackpot via undian Gacha yang dapat diverifikasi di akhir pool. Kunjungi Yield Explorer untuk melihat data APY langsung dari DeFiLlama di 10+ protokol.",

  "faq.q8": "Apakah Suivan non-kustodial?",
  "faq.a8": "Ya. Kamu yang pegang kendali asetmu lewat wallet. Smart contract tangani logika pool. Bahkan pembuat pool tidak bisa akses deposit peserta lain. Semua on-chain dan bisa diverifikasi.",

  "faq.q9": "Apa yang terjadi jika seseorang gagal bayar?",
  "faq.a9": "Jika ada yang lewatkan pembayaran, jaminannya dipotong otomatis. Jumlah terlewat masuk ke pool. Siklus berlanjut normal. Anggota lain terlindungi.",

  "faq.q10": "Apakah smart contract sudah diaudit?",
  "faq.a10": "Kontrak Suivan di-deploy di testnet Sui dan open-source. Mengikuti best practice keamanan Sui Move. Audit pihak ketiga direncanakan sebelum mainnet.",

  "faq.q11": "Berapa biaya menggunakan Suivan?",
  "faq.a11": "Kamu bayar nol gas. Setiap transaksi di Suivan disponsori oleh protokol. Saldo wallet-mu tidak tersentuh.",

  "faq.q12": "Bisakah saya membuat pool sendiri?",
  "faq.a12": "Tentu. Hubungkan wallet, buka /pools, klik +Create Pool. Atur jumlah deposit, peserta (2-50), dan durasi siklus. Bisa upload nama dan deskripsi via Walrus. Pool langsung aktif.",

  "faq.q13": "Apa itu Walrus dan bagaimana Suivan menggunakannya?",
  "faq.a13": "Walrus adalah penyimpanan blob terdesentralisasi Sui. Suivan pakai ini untuk simpan nama dan deskripsi pool. Permanen, tidak bisa diubah, bisa diverifikasi.",

  "faq.q14": "Di mana saya bisa mengikuti proyek ini?",
  "faq.a14": "Gabung di Telegram (t.me/sui_van) dan Discord (discord.gg/XxxM958bm). Ikuti @suivanprotocol di X. Kode open-source di GitHub. Kami project Sui Overflow 2026, menyambut feedback dan kontributor.",
  "faq.q15": "Bagaimana cara kerja jackpot gacha?",
  "faq.a15": "Setiap bulan, deposit menghasilkan yield via arbitrase flash loan DeepBook V3. Yield terkumpul sepanjang umur pool. Di akhir, satu orang menang semua via undian gacha berbobot. Peluangmu tergantung seberapa konsisten kamu bayar. Yang lewat 2+ pembayaran dapat nol tiket.",
  "faq.q16": "Bagaimana tingkat (tier) leaderboard saya dihitung?",
  "faq.a16": "Tiermu berdasarkan ketepatan pembayaran, yield, dan jumlah pool. Bayar 1-10 dapat poin terbanyak, 11-20 sedang, setelah 20 telat. Tier: Bronze (0+), Silver (100+), Gold (200+), Platinum (300+), Diamond (400+). Tier lebih tinggi = collateral yield lebih besar. Poin juga untuk tiket gacha.",

  "faq.contactTitle": "Masih ada pertanyaan?",
  "faq.contactDesc": "Bergabunglah dengan saluran komunitas Suivan untuk pembaruan, umpan balik, dan kolaborasi.",

  "landing.badge": "Sui Overflow 2026",
  "landing.title": "Pool ROSCA Global.\nNol Gas. Yield Nyata.",
  "landing.subtitle": "Suivan menghadirkan Rotating Savings & Credit Associations (ROSCA) di on-chain. Model keuangan informal yang kini di DeFi. Setor ke pool, hasilkan yield di protokol Sui, biarkan otomatisasi kelola siklus. Tanpa gas fee, tanpa perantara, tanpa lock-up. Smart contract transparan dengan transaksi disponsori. Tabungan komunitas bertemu DeFi di Sui.",
  "landing.explore": "Jelajahi Pool",
  "landing.how": "Cara Kerja",
  "landing.statPools": "POOL",
  "landing.statMembers": "ANGGOTA",
  "landing.statVolume": "VOLUME",
  "landing.statApy": "RATA APY",
  "landing.whyBadge": "dibangun_di_sui",
  "landing.whyTitle": "Ditenagai oleh",
  "landing.whySui": "Sui",
  "landing.whyDesc": "Model objek Sui mengubah setiap pool ROSCA menjadi entitas on-chain yang hidup. Dengan transaksi disponsori nol gas dan penyimpanan Walrus, Suivan membuat keuangan komunitas jadi sederhana.",
  "landing.feature1Title": "Mulai Cepat",
  "landing.feature1Desc": "Hubungkan Sui wallet dalam hitungan detik. Klaim 500 USDC dari faucet. Mulai menabung segera.",
  "landing.feature2Title": "Tx Sponsored",
  "landing.feature2Desc": "Nol gas — selalu. Setiap transaksi disponsori oleh protokol. Mulai menabung tanpa pernah bayar biaya.",
  "landing.feature3Title": "Yield DeFi",
  "landing.feature3Desc": "Dana idle pool dialihkan ke Cetus, NAVI, dan Scallop. APY nyata dari protokol Sui.",
  "landing.feature4Title": "Penyimpanan Walrus",
  "landing.feature4Desc": "Metadata pool disimpan permanen di Walrus. Terdesentralisasi, anti-rusak, selalu tersedia.",
  "landing.step1Title": "Gabung dengan Google",
  "landing.step1Copy": "Hubungkan Sui wallet apa pun. Instalasi gratis. Semua biaya gas disponsori oleh protokol.",
  "landing.step2Title": "Pilih Pool",
  "landing.step2Copy": "Pilih dari lingkaran ROSCA yang tersedia. Tinjau ketentuan, setor jaminan, dan komit ke siklus.",
  "landing.step3Title": "Kontribusi Bulanan",
  "landing.step3Copy": "Setiap siklus, setorkan bagian Anda. Lacak status: siap, tertunda, terkontribusi, atau terbayar.",
  "landing.step4Title": "Hasilkan Yield",
  "landing.step4Copy": "Dana idle pool menghasilkan yield DeFi secara otomatis. Strategi composable memaksimalkan hasil di seluruh protokol Sui.",
  "landing.sectionTitle": "Tabungan komunitas dalam empat langkah.",
  "landing.sectionSub": "Dari nol hingga yield — tanpa perlu pengetahuan kripto. Cukup login Google dan beberapa klik.",
  "landing.poolsBadge": "pool_langsung",
  "landing.poolsTitle": "Lingkaran ROSCA Aktif",
  "landing.poolsDesc": "Jelajahi pool nyata di Sui. Setiap pool adalah objek on-chain yang dapat diperiksa dengan status siklus transparan.",
  "landing.trustBadge": "lapisan_keamanan",
  "landing.trustTitle": "Dibangun untuk kepercayaan. Didukung Sui.",
  "landing.trustDesc": "Setiap kontribusi, pembayaran, dan siklus dicatat di ledger Sui. Kontrak pintar menegakkan aturan. Jaminan melindungi grup. Walrus membuat data pool permanen dan transparan.",
  "landing.trust1": "Non-Kustodial",
  "landing.trust1Desc": "Dana tetap di kontrak pintar — Suivan tidak pernah memegang aset Anda.",
  "landing.trust2": "Dijamin",
  "landing.trust2Desc": "Overcollateralization 125% memastikan komitmen. Tidak bayar? Jaminan menutupi grup.",
  "landing.trust3": "Dapat Diaudit",
  "landing.trust3Desc": "Setiap siklus, setiap pembayaran, setiap event yield — transparan penuh di Sui explorer.",
  "landing.ctaTitle": "Siap menabung dengan komunitas Anda?",
  "landing.ctaDesc": "Gabung pool ROSCA, kontribusi bulanan, dan hasilkan yield — semua tanpa dompet kripto.",
  "landing.ctaButton": "Mulai Gratis",
  "landing.ctaBadge": "tanpa_dompet",
  "landing.cylinderDesc": "Protokol pinjaman {chain} kelas atas dengan APY real-time dari DeFiLlama.",
  "landing.cylinderSupply": "Supply di {name} →",
  "landing.cylinderLive": "LIVE",
  "landing.cylinderSource": "SUMBER",
  "pools.title": "Jelajahi Pool ROSCA",
  "pools.subtitle": "Temukan pool tabungan bergilir dengan status siklus yang terlihat, progres peserta, dan sinyal APY.",
  "pools.totalPools": "TOTAL POOL",
  "pools.open": "TERBUKA",
  "pools.active": "AKTIF",
  "pools.usdc": "USDC",
  "pools.create": "+ Buat Pool Kustom",
  "pools.connectWallet": "Hubungkan dompet untuk membuat pool",
  "pools.join": "Gabung Pool",
  "pools.viewDetails": "Lihat Detail",
  "pools.emptyTitle": "Tidak ada pool ditemukan",
  "pools.emptyDesc": "Belum ada pool yang dibuat. Jadilah yang pertama!",
  "pools.emptyFilter": "Tidak ada pool {filter} saat ini.",
  "pools.joinTitle": "Gabung {name}",
  "pools.deposit": "Setoran per Siklus",
  "pools.collateral": "Jaminan Diperlukan",
  "pools.collateralDesc": "125% dari sisa setoran, dikembalikan di akhir siklus ditambah bonus yield",
  "pools.estimatedApy": "Estimasi APY",
  "pools.coinLabel": "Koin USDC",
  "pools.agree": "Dengan bergabung, Anda setuju untuk melakukan setoran bulanan selama {count} bulan",
  "pools.createTitle": "Buat Pool Kustom",
  "pools.totalValue": "Total Nilai Pool",
  "pools.poolDuration": "Durasi Pool",
  "pools.requiredCollateral": "Jaminan Diperlukan (125%)",

  "detail.back": "Kembali ke Pool",
  "detail.poolInfo": "Informasi Pool",
  "detail.deposit": "SETORAN",
  "detail.members": "ANGGOTA",
  "detail.cycle": "SIKLUS",
  "detail.funds": "DANA",
  "detail.capacity": "Kapasitas Pool",
  "detail.yieldSection": "Sinyal Yield dan Siklus",
  "detail.yield": "YIELD",
  "detail.estApy": "EST APY",
  "detail.collateral": "JAMINAN",
  "detail.participants": "Peserta ({count})",
  "detail.noParticipants": "Belum ada peserta. Jadilah yang pertama!",
  "detail.yourStatus": "Status Anda",
  "detail.activeParticipant": "Peserta Aktif",
  "detail.youAreIn": "Anda adalah bagian dari pool ROSCA ini",
  "detail.collateralLocked": "Jaminan Terkunci",
  "detail.totalDeposited": "Total Disetor",
  "detail.receivedPayout": "Sudah Dibayar",
  "detail.yes": "Ya",
  "detail.notYet": "Belum",
  "detail.makeDeposit": "Lakukan Setoran Siklus",
  "detail.collateralAvailable": "Jaminan Tersedia",
  "detail.collateralReturned": "Jaminan + bonus yield Anda telah dikembalikan secara otomatis saat pool berakhir.",
  "detail.notParticipant": "Anda bukan peserta di pool ini.",
  "detail.joinThisPool": "Gabung Pool Ini",
  "detail.yourWallet": "Dompet Anda",
  "detail.usdcBalance": "Saldo USDC",
  "detail.coinsAvailable": "{count} koin tersedia",
  "detail.getStarted": "Mulai",
  "detail.connectPrompt": "Hubungkan dompet Anda untuk bergabung dengan pool ini atau lihat status Anda",
  "detail.chartDisclaimer": "Proyeksi simulasi berdasarkan metrik pool saat ini. Data deret waktu nyata akan muncul setelah beberapa siklus.",
  "ai.badge": "SUI YIELD EXPLORER",
  "ai.title": "SUI Yield Explorer",
  "ai.subtitle": "Data APY langsung dari protokol Sui DeFi, dideploy via arbitrase flash loan DeepBook V3.",
  "ai.loading": "Mengambil data yield...",
  "ai.errorTitle": "KESALAHAN",
  "ai.avgApy": "RATA-RATA APY",
  "ai.maxApy": "APY MAKS",
  "ai.protocols": "PROTOKOL",
  "ai.totalTvl": "TOTAL TVL",
  "ai.protocolYields": "Yield Protokol",
  "ai.trend": "Tren",
  "ai.marketConditions": "Kondisi Pasar",
  "ai.volatilityIndex": "Indeks Volatilitas",
  "ai.gasPrice": "Harga Referensi Gas",
  "ai.direction": "Arah",
  "ai.topProtocol": "Teratas",
  "ai.howSuivanUses": "Bagaimana Suivan Mendeploy Yield",
  "ai.howSuivanUsesDesc": "Dana pool dideploy ke protokol Sui DeFi melalui arbitrase flash loan DeepBook V3. Eksekusi otomatis dan di-rebalance terus-menerus.",
  "ai.step1Title": "Tarik Dana",
  "ai.step1Desc": "Dana ditarik secara atomik. Jika gagal, seluruh transaksi di-rollback.",
  "ai.step2Title": "Arbitrase",
  "ai.step2Desc": "Flash loan dipinjam dari DeepBook. Arbitrase dieksekusi di DEX dan lending pool secara bersamaan.",
  "ai.step3Title": "Profit",
  "ai.step3Desc": "Profit masuk ke jackpot kumulatif. Principal kembali ke pool.",
  "ai.step4Title": "Jackpot",
  "ai.step4Desc": "Di akhir pool, satu pemenang gacha mengambil semua yield. Bobot ditentukan oleh skor pembayaran tepat waktu.",
  "ai.deepbookTitle": "DeepBook V3",
  "ai.deepbookMidPrice": "Harga Tengah",
  "ai.deepbookSpread": "Spread",
  "ai.deepbookBidDepth": "Kedalaman Bid",
  "ai.deepbookAskDepth": "Kedalaman Ask",
  "ai.deepbookLink": "Lihat DeepBook Explorer",
  "ai.sortedBy": "Diurutkan dari",
  "ai.howItWorks": "Bagaimana Suivan Mendeploy Yield",
  "ai.autoNote": "Eksekusi otomatis. Rute di-rebalance terus-menerus melalui arbitrase flash loan.",
  "ai.seeDeepBookFlow": "Lihat Alur Lengkap",
  "ai.explorePools": "Jelajahi Pool",
  "demo.badge": "panduan_demo",
  "demo.subtitle": "Lima langkah dari nol hingga yield. Tidak perlu pengetahuan kripto.",
  "demo.step": "Langkah",
  "demo.step1Detail": "Hubungkan Sui wallet dalam hitungan detik. Instal, hubungkan, selesai. Semua biaya gas disponsori.",
  "demo.step1Action": "Coba Login Google",
  "demo.step2Detail": "Jelajahi pool (Kecil: 10 USDC, Sedang: 50 USDC, Besar: 100 USDC). Setor jaminan sekali. Semua gas disponsori.",
  "demo.step2Action": "Gabung Sponsored",
  "demo.step3Detail": "Setiap siklus, setorkan bagianmu. Tidak bayar? Jaminan dipotong otomatis.",
  "demo.step3Action": "Lakukan Setoran",
  "demo.step4Detail": "Satu peserta menang setiap siklus. Seleksi via Seal RNG yang bisa diverifikasi. Pemenang terima semua deposit siklus.",
  "demo.step4Action": "Pilih Pemenang",
  "demo.step5Detail": "Dana idle menghasilkan yield via DeFi Sui. APY nyata dari DeFiLlama. Di akhir pool, jaminan kembali plus bagian yield-mu.",
  "demo.step5Action": "Lihat Dashboard Yield",
  "demo.feature1Title": "Biaya Gas Nol",
  "demo.feature1Desc": "Nol gas, selalu. Gabung pool tanpa pernah memiliki SUI.",
  "demo.feature2Title": "Yield DeFi",
  "demo.feature2Desc": "Dana idle dialihkan ke protokol Sui. APY nyata dari DeFiLlama.",
  "demo.feature3Title": "Metadata On-Chain",
  "demo.feature3Desc": "Detail pool disimpan di Walrus. Permanen dan terdesentralisasi.",
  "leaderboard.badge": "LEADERBOARD",
  "leaderboard.title": "Peringkat Peserta",
  "leaderboard.subtitle": "Peringkat berdasarkan ketepatan pembayaran, yield, dan reputasi komunitas. Bayar sebelum tanggal 20 untuk naik peringkat.",
  "leaderboard.statPools": "POOL AKTIF",
  "leaderboard.statUsers": "ANGGOTA",
  "leaderboard.statEarned": "TOTAL YIELD",
  "leaderboard.statAvgApy": "RATA APY",
  "leaderboard.tierDiamond": "Berlian",
  "leaderboard.tierPlatinum": "Platinum",
  "leaderboard.tierGold": "Emas",
  "leaderboard.tierSilver": "Perak",
  "leaderboard.tierBronze": "Perunggu",
  "leaderboard.tierDesc": "Anggota dengan rekor pembayaran luar biasa dan akumulasi yield tinggi.",
  "leaderboard.cycleTitle": "Siklus Saat Ini",
  "leaderboard.cycleDeadline": "Batas Pembayaran",
  "leaderboard.cycleDrawing": "Pengundian Pemenang",
  "leaderboard.cyclePot": "Hadiah Pemenang",
  "leaderboard.yourRank": "Peringkat Anda",
  "leaderboard.yourPoints": "Poin",
  "leaderboard.yourYield": "Yield Anda",
  "leaderboard.yourTier": "Tingkat Anda",
  "leaderboard.notConnected": "Hubungkan dompet untuk melihat peringkat",
  "leaderboard.rank": "PERINGKAT",
  "leaderboard.member": "ANGGOTA",
  "leaderboard.tier": "TINGKAT",
  "leaderboard.points": "POIN",
  "leaderboard.payment": "PEMBAYARAN",
  "leaderboard.yield": "YIELD",
  "leaderboard.onTime": "TEPAT WAKTU",
  "leaderboard.pools": "POOL",
  "leaderboard.early": "Tepat Waktu",
  "leaderboard.late": "Terlambat",
  "leaderboard.noData": "Belum ada peserta. Gabung pool untuk muncul di papan peringkat.",
  "leaderboard.rulesTitle": "Cara Peringkat Bekerja",
  "leaderboard.rulesPayment": "Iuran Bulanan",
  "leaderboard.rulesPaymentDesc": "Setiap anggota membayar iuran bulanan. Pembayaran harus diterima sebelum tanggal 20. Pembayaran terlambat dipotong dari collateral.",
  "leaderboard.rulesPoints": "Sistem Poin",
  "leaderboard.rulesPointsDesc": "Bayar 1–10: +100 pts | 11–15: +75 pts | 16–20: +50 pts | Setelah 20 (telat): +10 pts. Poin kumulatif menentukan tingkat Anda.",
  "leaderboard.rulesDrawing": "Pengundian Pemenang",
  "leaderboard.rulesDrawingDesc": "Setiap tanggal 25, satu anggota dipilih secara acak untuk menerima total pot (peserta × iuran bulanan). Semua anggota tetap dalam siklus.",
  "leaderboard.rulesYield": "Perhitungan Yield",
  "leaderboard.rulesYieldDesc": "Dua yield di akhir pool. Yield Collateral: hasil dasar × pengali tier. Yield Kumulatif: dari semua iuran. Tier lebih tinggi = pengali lebih besar.",
  "leaderboard.rulesGacha": "Jackpot Gacha",
  "leaderboard.rulesGachaDesc": "Semua yield dari iuran dikumpulkan jadi jackpot. Di akhir pool, satu pemenang diundi via lotere berbobot. Skor pembayaran menentukan tiketmu. Makin konsisten, makin tinggi peluang. Yang lewat 2+ pembayaran dapat nol tiket.",
  "leaderboard.cta": "Gabung Pool",


  "simulator.badge": "SIMULATOR",
  "simulator.title": "Berapa saldo dompet yang dibutuhkan?",
  "simulator.subtitle": "Hitung persis berapa USDC + SUI yang Anda perlukan sebelum bergabung dengan pool ROSCA. Tanpa kejutan, tanpa biaya tersembunyi.",
  "simulator.poolConfig": "Konfigurasi Pool",
  "simulator.depositLabel": "Setoran per Siklus (USDC)",
  "simulator.participantsLabel": "Jumlah Peserta",
  "simulator.cycleLabel": "Durasi Siklus (hari)",
  "simulator.gasSponsor": "Transaksi Disponsori",
  "simulator.gasSponsorDesc": "Semua transaksi disponsori. Kamu tidak pernah bayar gas. Protokol yang tanggung.",
  "simulator.breakdown": "Rincian Kebutuhan Dompet",
  "simulator.totalUpfront": "Total Dana Dibutuhkan",
  "simulator.needToPrepare": "Anda perlu menyiapkan",
  "simulator.deposit": "Setoran Siklus",
  "simulator.collateral": "Jaminan (125%)",
  "simulator.gas": "Biaya Gas",
  "simulator.gasFree": "Semua tx disponsori",
  "simulator.usdc": "USDC",
  "simulator.sui": "SUI",
  "simulator.poolSummary": "Ringkasan Pool",
  "simulator.totalPool": "Total Nilai Pool",
  "simulator.totalCycles": "Total Siklus",
  "simulator.poolDuration": "Durasi Pool",
  "simulator.yourPosition": "Posisi Anda",
  "simulator.youPay": "Bayar Per Siklus",
  "simulator.youEarn": "Total yang Anda Terima",
  "simulator.compareTitle": "Nol gas di Sui",
  "simulator.compareDesc": "Biaya tx Sui ~0,0001 SUI (pecahan sen). Ethereum L1 rata-rata ~$1,50 per tx.",
  "simulator.suiFee": "Biaya Sui",
  "simulator.ethFee": "Biaya Ethereum",
  "simulator.savings": "Efisiensi",
  "simulator.cta": "Jelajahi Pool Nyata",
  "simulator.collateralNote": "125% dari sisa komitmen kontribusi, dikembalikan di akhir siklus",
  "simulator.collateralDetail": "Jaminan melindungi semua anggota. Jika kamu melewatkan pembayaran, setoran dipotong dari jaminan. Jaminan yang tidak digunakan + yield proporsional dikembalikan saat pool berakhir.",

  "faucet.badge": "FAUCET TEST",
  "faucet.title": "Dapatkan Token Tes",
  "faucet.subtitle": "Klaim 500 USDC untuk testing. Semua transaksi disponsori, nol biaya gas. Jelajahi pool Suivan sebelum mainnet.",
  "faucet.claimUsdc": "Klaim 10,000 Test USDC",
  "faucet.claimSui": "Klaim 500 USDC",
  "faucet.walletRequired": "Hubungkan dompet Anda untuk klaim token tes.",
  "faucet.success": "Token berhasil diklaim!",
  "faucet.error": "Permintaan faucet gagal",
  "faucet.cooldown": "Cooldown aktif. Coba lagi dalam {time}s.",
  "faucet.description": "Semua token di halaman ini hanya testnet \u2014 tidak bernilai riil. Gunakan untuk simulasi pembuatan pool, join, dan yield.",
  "faucet.usdcLabel": "USDC (Testnet)",
  "faucet.usdcDesc": "Stablecoin USDC untuk deposit dan jaminan pool",
  "faucet.suiLabel": "TEST_SUI",
  "faucet.suiDesc": "Gas disponsori — kamu tidak pernah bayar",
  "faucet.recentTitle": "Klaim Terbaru",
  "faucet.recentEmpty": "Belum ada klaim. Mulai dengan menghubungkan dompet Anda.",
  "faucet.balanceTitle": "Saldo Anda",
  "faucet.goToPools": "Ke Pools",

  "profile.badge": "DASHBOARD ANDA",
  "profile.title": "Profil Anda",
  "profile.subtitle": "Perjalanan tabungan on-chain Anda: pool yang diikuti, siklus dimenangkan, dan yield yang dihasilkan di jaringan Sui.",
  "profile.titleWithAddr": "Profil Anda — {addr}",
  "profile.connectPrompt": "Hubungkan dompet Anda untuk melihat profil Suivan.",
  "profile.statsPools": "Pool Diikuti",
  "profile.statsWon": "Siklus Menang",
  "profile.statsSaved": "Total Ditabung",
  "profile.statsYield": "Yield Didapat",
  "profile.nftTitle": "Pencapaian",
  "profile.nftEmpty": "Belum ada pencapaian. Gabung pool untuk dapatkan pencapaian Suivan pertama Anda.",
  "profile.activityTitle": "Aktivitas Terbaru",
  "profile.activityEmpty": "Belum ada aktivitas. Join pool, menang siklus, dan klaim badge akan muncul di sini.",
  "profile.noActivity": "Belum ada aktivitas. Gabung pool untuk memulai!",
  "profile.infoTitle": "Info Akun",
  "profile.infoAddress": "Alamat Dompet",
  "profile.infoMemberSince": "Anggota Sejak",
  "profile.infoPools": "Pool Aktif",
  "profile.infoNetwork": "Jaringan",
};

const translations: Record<Language, Record<string, string>> = { en, id };

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    const stored = localStorage.getItem("suivan-language") as Language | null;
    return stored === "en" || stored === "id" ? stored : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("suivan-language", lang);
  };

  const t = (key: string, params?: Record<string, string | number>) => {
    let text = translations[language]?.[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t } as LanguageContextType}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
